import { defineConfig } from 'eslint/config'
import eslint from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import prettier from 'eslint-config-prettier'

export default defineConfig([
  // Global ignores
  {
    ignores: [
      'dist',
      'node_modules',
      'coverage',
      '*.gen.ts', // TanStack Router generated files
      'src/routeTree.gen.ts',
      'public',
      'e2e/', // Playwright tests (not in tsconfig)
      'playwright.config.ts', // Playwright config (not in tsconfig)
      'vite.config.ts', // Handled by tsconfig.node.json
      'src/components/ui/**', // Auto-generated by shadcn
    ],
  },

  // Base JavaScript config
  eslint.configs.recommended,

  // TypeScript type-checked configs (scoped to TS files only)
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      // React Hooks rules
      ...reactHooks.configs.recommended.rules,

      // Accessibility rules
      ...jsxA11y.flatConfigs.recommended.rules,

      // TypeScript specific overrides
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports' },
      ],
      '@typescript-eslint/no-misused-promises': [
        'error',
        { checksVoidReturn: { attributes: false } },
      ],

      // General rules
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // Configuration files (JS) - no type checking
  {
    files: ['*.config.{js,mjs}'],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Test files
  {
    files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}', 'src/test/**/*'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  // Prettier must be last to override formatting rules
  prettier,
])
